services:
  - type: web
    name: deepfake-detector-api
    env: python
    rootDir: ..
    plan: free
    buildCommand: 
      poetry install
      pip install -r requirements.txt
    startCommand: uvicorn api.deepfake_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /docs
    autoDeploy: true
    disk:
      name: model-storage
      mountPath: /opt/render/model-storage
      sizeGB: 1 
